name: license

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check License
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix
      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'Automatic application of license header'
