name: license

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check License
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix
